# Generated by Django 4.2.5 on 2023-09-10 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="position",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
