# Generated by Django 4.2.5 on 2023-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0003_crew_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={
                "ordering": ["position"],
                "verbose_name": "crew_member",
                "verbose_name_plural": "crew_members",
            },
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("VEGETARIAN", "Vegetarian"),
                    ("NO_MEAL", "No meal"),
                ],
                default="STANDARD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_class",
            field=models.CharField(
                choices=[("ECONOMY", "Economy"), ("BUSINESS", "Business")],
                default="ECONOMY",
                max_length=8,
            ),
        ),
    ]
