# Generated by Django 4.2.5 on 2023-09-15 20:53

import airplane.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airplane", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airplane.models.airplane_image_file_path
            ),
        ),
    ]
